optimized

diff --git a/formula/ncurses.yml b/formula/ncurses.yml
--- a/formula/ncurses.yml
+++ b/formula/ncurses.yml
@@ -1,21 +1,51 @@
+pkgtype: lib
 summary: Text-based UI library
 git-url: https://github.com/mirror/ncurses
 web-url: https://www.gnu.org/software/ncurses
-src-url: https://ftp.gnu.org/gnu/ncurses/ncurses-6.4.tar.gz
-src-sha: 6931283d9ac87c5073f30b6290c4c75f21632bb4fc3603ac8100812bed248159
+src-url: https://ftp.gnu.org/gnu/ncurses/ncurses-6.5.tar.gz
+src-sha: 136d91bc269a9a5785e5f9e980bc76ab57428f604ce3e5a5a90cebc767971cc6
 license: MIT
 
+do12345: |
+    isCrossBuild || return 0
+
+    {
+        # https://github.com/termux/termux-packages/issues/4487
+        if command -v tic > /dev/null ; then
+            run tic -V
+            [ '6.2.20200212' != "$(printf '%s\n' '6.2.20200212' "$(tic -V | cut -d' ' -f2)" | sort -V | head -n 1)" ]
+        else
+            warn 'tic command not found. we need build it now.'
+        fi
+    } || return 0
+
+    unset TERMINFO
+    configure \
+        --with-pkg-config-libdir="$NATIVE_INSTALL_DIR/lib/pkgconfig" \
+        ac_cv_header_fcntl_h=yes \
+        ac_cv_header_unistd_h=yes \
+        ac_cv_header_sys_time_h=yes
+
 dopatch: |
-    if isCrossBuild && [ "$TARGET_PLATFORM_NAME" = openbsd ] ; then
-        gsed -i 's|-Bshareable|-shared|g' configure
-        export LD="$CC"
+    if isCrossBuild ; then
+        gsed -i 's|cf_ok_build_cc=unknown|cf_ok_build_cc=yes|' configure
+
+        if [ "$TARGET_PLATFORM_NAME" = openbsd ] ; then
+            gsed -i 's|-Bshareable|-shared|g' configure
+            export LD="$CC"
+        fi
     fi
+
+prepare: |
+    export BUILD_CC="$CC_FOR_BUILD"
+    export BUILD_CFLAGS="$CFLAGS_FOR_BUILD"
+    export BUILD_CPPFLAGS="$CPPFLAGS_FOR_BUILD"
+    export BUILD_LDFLAGS="$LDFLAGS_FOR_BUILD"
+    unset  BUILD_LIBS
 
     unset TERMINFO
 
     export LDCONFIG=true
-
-    gsed -i 's|cf_ok_build_cc=unknown|cf_ok_build_cc=yes|' configure
 
 install: |
     configure \
